# Don't touch this file otherwise your device may stop working.
# Use override.yaml to modify required settings.
# You can find a working configuration in /usr/share/kvmd/configs.default/kvmd.

override: !include [override.d, override.yaml]

logging: !include logging.yaml

kvmd:
    auth: !include auth.yaml

    info:
        fan:
            unix: /run/kvmd/fan.sock

    hid:
        type: otg

    atx:
        type: gpio

    msd:
        type: otg

    streamer:
        h264_bitrate:
            default: 5000
        whip_url: "http://localhost:7777/whip/pikvm"
        ffmpeg_input_format: "v4l2"
        ffmpeg_codec: "libvpx"
        rtsp_port: 8554
        cmd:
            - "/usr/bin/v4l2-ctl"
            - "--device=/dev/video0"
            - "--query-dv-timing"
            - "&"
            - "/usr/bin/v4l2-ctl"
            - "--device=/dev/video0"
            - "--set-dv-bt-timing=query"
            - "&"
            - "/usr/bin/whipinto"
            - "-w"
            - "{whip_url}"
            - "-i"
            - "rtsp-listen://127.0.0.1:{rtsp_port}"
            - "&"
            - "/usr/bin/ffmpeg"
            - "-f"
            - "{ffmpeg_input_format}"
            - "-i"
            - "/dev/video0"
            - "-video_size"
            - "{resolution}"
            - "-r"
            - "{desired_fps}"
            - "-c:v"
            - "{ffmpeg_codec}"
            - "-b:v"
            - "{h264_bitrate}k"
            - "-deadline"
            - "realtime"
            - "-cpu-used"
            - "4"
            - "-f"
            - "rtsp"
            - "-pkt_size"
            - "1200"
            - "rtsp://127.0.0.1:{rtsp_port}"

    gpio:
        scheme:
            __v3_usb_breaker__:
                pin: 5
                mode: output
                initial: true
                pulse: false


media:
    memsink:
        h264:
            sink: "kvmd::ustreamer::h264"


vnc:
    memsink:
        jpeg:
            sink: "kvmd::ustreamer::jpeg"
        h264:
            sink: "kvmd::ustreamer::h264"
