# Don't touch this file otherwise your device may stop working.
# Use override.yaml to modify required settings.
# You can find a working configuration in /usr/share/kvmd/configs.default/kvmd.

override: !include [override.d, override.yaml]

logging: !include logging.yaml

kvmd:
    auth: !include auth.yaml

    info:
        fan:
            unix: /run/kvmd/fan.sock

    hid:
        type: otg

    atx:
        type: gpio

    msd:
        type: otg

    streamer:
        h264_bitrate:
            default: 5000
        whip_url: "http://localhost:7777/whip/pikvm"
        whip_token: ""
        ffmpeg_input_format: "v4l2"
        ffmpeg_codec: "libvpx-vp8"
        cmd:
            - "/usr/bin/ffmpeg"
            - "-f"
            - "{ffmpeg_input_format}"
            - "-input_format"
            - "mjpeg"
            - "-video_size"
            - "{resolution}"
            - "-framerate"
            - "{desired_fps}"
            - "-i"
            - "/dev/kvmd-video"
            - "-c:v"
            - "{ffmpeg_codec}"
            - "-b:v"
            - "{h264_bitrate}k"
            - "-deadline"
            - "realtime"
            - "-cpu-used"
            - "4"
            - "-f"
            - "rtp"
            - "-"
            - "|"
            - "/usr/bin/whipinto"
            - "-i"
            - "-"
            - "-w"
            - "{whip_url}"
            - "-t"
            - "{whip_token}"
            - "--exit-on-parent-death"
            - "--process-name-prefix={process_name_prefix}"

    gpio:
        scheme:
            __v3_usb_breaker__:
                pin: 5
                mode: output
                initial: true
                pulse: false


media:
    memsink:
        h264:
            sink: "kvmd::ustreamer::h264"


vnc:
    memsink:
        jpeg:
            sink: "kvmd::ustreamer::jpeg"
        h264:
            sink: "kvmd::ustreamer::h264"
